# Generated by Django 3.1.7 on 2021-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210402_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='venue',
            field=models.DateTimeField(),
        ),
    ]
